== Bibliography

[bibliography]
* [[[GH-React]]]
Github project page of the React library,
retrieved on 2017-05-15
from https://github.com/facebook/react.
Archived at http://web.archive.org/web/20170515141250/https://github.com/facebook/react.
* [[[GH-ng]]]
Github project page of the Angular framework,
retrieved on 2017-05-15
from https://github.com/angular/angular.
Archived at http://web.archive.org/web/20170515141421/https://github.com/angular/angular.
* [[[GH-ngjs]]]
Github project page of the AngularJS framework,
retrieved on 2017-05-15
from https://github.com/angular/angular.js.
Archived at http://web.archive.org/web/20170515141425/https://github.com/angular/angular.js.
* [[[GH-Vue]]]
Github project page of the Vue.js framework,
retrieved on 2017-05-15
from https://github.com/vuejs/vue.
Archived at http://web.archive.org/web/20170515141530/https://github.com/vuejs/vue.
* [[[GH-Ember]]]
Github project page of the Ember.js framework,
retrieved on 2017-05-15
from https://github.com/emberjs/ember.js.
Archived at http://web.archive.org/web/20170515142927/https://github.com/emberjs/ember.js.
* [[[GH-Bckbn]]]
Github project page of the Backbone.js framework,
retrieved on 2017-05-15
from https://github.com/jashkenas/backbone.
Archived at http://web.archive.org/web/20170515144325/https://github.com/jashkenas/backbone.
* [[[GH-Aur]]]
Github project page of the Aurelia framework,
retrieved on 2017-05-15
from https://github.com/aurelia/framework.
Archived at http://web.archive.org/web/20170515142932/https://github.com/aurelia/framework.
* [[[GH-Sve]]]
Github project page of the Svelte framework,
retrieved on 2017-05-15
from https://github.com/sveltejs/svelte.
Archived at http://web.archive.org/web/20170515142936/https://github.com/sveltejs/svelte.
* [[[GH-Cycle]]]
Github project page of the Cycle.js framework,
retrieved on 2017-05-15
from https://github.com/cyclejs/cyclejs.
Archived at http://web.archive.org/web/20170515142942/https://github.com/cyclejs/cyclejs.
* [[[GTREND-EmberBckbn]]]
Google Trends diagram on ember.js vs backbone.js,
retrieved on 2017-05-15
from https://trends.google.com/trends/explore?date=2010-05-16%202017-05-15&q=ember.js,backbone.js.
* [[[REE12]]]
Rick Reed,
"Scaling to Millions of Simultaneous Connections",
presented at Erlang Factory, San Francisco Bay Area, California, USA, 2012.
Slides available at http://web.archive.org/web/20170515204931/http://www.erlang-factory.com/upload/presentations/558/efsf2012-whatsapp-scaling.pdf.
* [[[OGR17]]]
Stephen O'Grady,
"The RedMonk Programming Language Rankings: January 2017",
RedMonk, Portlande, Maine, USA, 2017.
Report available at http://web.archive.org/web/20170515205641/http://redmonk.com/sogrady/2017/03/17/language-rankings-1-17/.
* [[[VEN09]]]
Bill Venners,
"Twitter on Scala - A Conversation with Steve Jenson, Alex Payne, and Robey Pointer",
Artima, Inc., Mountain View, California, USA, 2009.
Article available at http://web.archive.org/web/20170515210829/http://www.artima.com/scalazine/articles/twitter_on_scala.html.
* [[[KOP15]]]
Alexander Kops,
"From Java to Scala in Less Than Three Months",
presented at Scala Days, Amsterdam, Netherlands, 2015.
Slides available at http://web.archive.org/web/20170515211336/https://www.slideshare.net/ZalandoTech/zalando-tech-from-java-to-scala-in-less-than-three-months.
* [[[GOE14]]]
Brian Goetz and Java Community Process contributors,
"JSR-000335 Lambda Expressions for the Java^TM^ Programming Language",
Oracle Corporation, Redwood City, California, USA, 2014.
Available at https://jcp.org/aboutJava/communityprocess/final/jsr335/index.html.
* [[[ECM15]]]
"ECMAScript® 2015 Language Specification",
Ecma International, Geneva, Switzerland, 2015.
Available at https://www.ecma-international.org/ecma-262/6.0/.
* [[[ECM11]]]
"ECMAScript® Language Specification (5.1 Edition)",
Ecma International, Geneva, Switzerland, 2011.
Available at https://www.ecma-international.org/ecma-262/5.1/.
* [[[CH13]]]
Ben Christensen, Jafar Husain,
"Reactive Programming in the Netflix API with RxJava",
Netflix Inc., Los Gatos, California, USA, 2013.
Blog post available at http://web.archive.org/web/20170516092032/https://medium.com/netflix-techblog/reactive-programming-in-the-netflix-api-with-rxjava-7811c3a1496a.
* [[[GH-Redux]]]
Github project page of the Redux state management library,
retrieved on 2017-05-16
from https://github.com/reactjs/redux.
Archived at http://web.archive.org/web/20170516092915/https://github.com/reactjs/redux.
* [[[GH-MobX]]]
Github project page of the MobX state management library,
retrieved on 2017-05-16
from https://github.com/mobxjs/mobx.
Archived at http://web.archive.org/web/20170516093551/https://github.com/mobxjs/mobx.
* [[[GRE16]]]
Sascha Greif,
"State of JavaScript survey", 2016.
Survey results available at http://stateofjs.com/.
* [[[GTREND-Elm]]]
Google Trends diagram on Elm,
retrieved on 2017-05-16
from https://trends.google.com/trends/explore?q=%2Fm%2F0ncc1sv.
* [[[WH00]]]
Zhanyong Wan, Paul Hudak,
"Functional reactive programming from first principles",
Yale University, New Haven, Connecticut, USA, 2000.
Archived at http://web.archive.org/web/20170609160109/https://pdfs.semanticscholar.org/b3b5/59104528d31f7db7fbe208377abdc4a00e15.pdf.
* [[[GH-RxJava]]]
Github project page of the RxJava library,
retrieved on 2017-06-10
from https://github.com/ReactiveX/RxJava.
Archived at http://web.archive.org/web/20170610141854/https://github.com/ReactiveX/RxJava.
* [[[GH-RxSwift]]]
Github project page of the RxSwift library,
retrieved on 2017-06-10
from https://github.com/ReactiveX/RxSwift.
Archived at http://web.archive.org/web/20170610141951/https://github.com/ReactiveX/RxSwift.
* [[[GH-RxJS]]]
Github project page of the RxJS library,
retrieved on 2017-06-10
from https://github.com/ReactiveX/rxjs.
Archived at http://web.archive.org/web/20170610142030/https://github.com/ReactiveX/rxjs.
* [[[GTREND-Rx]]]
Google Trends diagram on RxJava, RxSwift and RxJS,
retrieved on 2017-06-10
from https://trends.google.com/trends/explore?date=2013-06-10%202017-06-10&q=RxJava,RxSwift,RxJS.
* [[[Rx-Intro]]]
Introduction page to the ReactiveX collection of libraries,
retrieved on 2017-06-11
from http://reactivex.io/intro.html.
Archived at http://web.archive.org/web/20170611122140/http://reactivex.io/intro.html.
